# workflow name
name: Generate release-artifacts

on:
    workflow_dispatch:

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
            xgo_version: latest
            go_version: 1.18
            prefix: prometheus-ecs-discovery
            targets: linux/arm64
            race: false
            ldflags: -s -w
            buildmode: default
            trimpath: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: /build/prometheus-ecs-discovery-linux-arm64
