# workflow name
name: Generate release-artifacts

on:
    workflow_dispatch:

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amr64'
            name: 'ecs-sd-prometheus'
      - name: Release
        uses: softprops/action-gh-release@v1