name: Docker Buildx & Publish Image

on:
  push:
    branches: [ master ]

jobs:   
  build:    
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: hub.docker.com
      DOCKER_IMAGE: bitkill/prometheus-ecs-discovery
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:    
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Prepare      
      if: success()      
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}

    - name: Run Buildx (push image)      
      if: success()
      run: |
        docker build \
          --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
          --platform linux/amd64,linux/arm64/v8,linux/arm64/v8,linux/arm/v7 \
          --file ./Dockerfile \
          --output type=image,push=true .
