name: Docker Buildx & Publish Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write
  checks: read

jobs:   
  build:    
    runs-on: ubuntu-latest


    steps:    
    - id: read-docker-image-identifiers
      name: Read Docker Image Identifiers
      run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Github Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: true
        tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.run_number }},ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
